<a href="https://colab.research.google.com/github/Goodness18/Pandas-Analysis/blob/main/movieawards.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Load the films.csv into a pandas dataframe and call it data

import pandas as pd
import io
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

Saving Films data.csv to Films data.csv

In [ ]:
data = pd.read_csv('Films data.csv')
data

,Unnamed: 0,Year,Length,Title,Subject,Actor,Actress,Director,Popularity,Awards
0,0,1990,111.0,Tie Me Up! Tie Me Down!,Comedy,"Banderas, Antonio","Abril, Victoria","Almodóvar, Pedro",68.0,No
1,1,1991,113.0,High Heels,Comedy,"Bosé, Miguel","Abril, Victoria","Almodóvar, Pedro",68.0,No
2,2,1983,104.0,"Dead Zone, The",Horror,"Walken, Christopher","Adams, Brooke","Cronenberg, David",79.0,No
3,3,1979,122.0,Cuba,Action,"Connery, Sean","Adams, Brooke","Lester, Richard",6.0,No
4,4,1978,94.0,Days of Heaven,Drama,"Gere, Richard","Adams, Brooke","Malick, Terrence",14.0,No
...,...,...,...,...,...,...,...,...,...,...
1654,1654,1932,226.0,"Shadow of the Eagle, The",Action,"Wayne, John",\N,\N,19.0,No
1655,1655,1989,103.0,Blood & Guns,Action,"Welles, Orson",\N,\N,43.0,No
1656,1656,1988,78.0,Hot Money,Drama,"Welles, Orson",\N,\N,19.0,No
1657,1657,1977,75.0,Comedy Tonight,Comedy,"Williams, Robin",\N,\N,18.0,No
1658,1658,1991,65.0,Robin Williams,Comedy,"Williams, Robin",\N,\N,4.0,No

How many nulls are there in each column of data?

In [ ]:
#Use isnull() method to see the boolean representation of nulls
#Apply sum() function to the boolean values to see the sum of nulls in each column.
null_counts = data.isnull().sum()
null_counts

Unnamed: 0     0
Year           0
Length        67
Title          0
Subject        2
Actor          8
Actress        0
Director       0
Popularity     6
Awards         0
dtype: int64

Determine the average popularity for each movie subject category and identify the top 3 most popular subjects.

In [ ]:
# Group by 'Subject' using groupby() method.
# Calculate the average of Popularity using mean() method.

subject_category = data.groupby('Subject')['Popularity'].mean()
#Use sort_values() method to sort the Subjects by average popularity values in descending order.
# Use head() method to show the top 3 most popular subjects.

subject_category_top_3 = subject_category.sort_values(ascending = False).head(3)
print('Group By Movie Subject:')
print(subject_category)
print('\nTop 3 Movie Subject by Populairty:')
print(subject_category_top_3)

Group By Movie Subject:
Subject
Action             38.950980
Adventure          63.500000
Comedy             42.828571
Crime              66.000000
Drama              44.150307
Fantasy            57.000000
Horror             46.526316
Music              46.139535
Mystery            40.691589
Romance            62.000000
Science Fiction    42.500000
Short              62.000000
War                41.294118
Western            44.271186
Westerns           38.500000
Name: Popularity, dtype: float64

Top 3 Movie Subject by Populairty:
Subject
Crime        66.0
Adventure    63.5
Romance      62.0
Name: Popularity, dtype: float64

Inspect the first and last 5 rows of the dataframe.
Remove the records having nulls in Length, Subject, Actor and Popularity columns.
Replace nulls in Actress and Directory columns with ‘Unknown’.

In [ ]:
#Use the head() and tail() methods.
print('Top 5 Rows')
print(data.head(5))
print('\nBottom 5 Rows')
print(data.tail(5))

Top 5 Rows
   Unnamed: 0  Year  Length                    Title Subject  \
0           0  1990   111.0  Tie Me Up! Tie Me Down!  Comedy
1           1  1991   113.0               High Heels  Comedy
2           2  1983   104.0           Dead Zone, The  Horror
3           3  1979   122.0                     Cuba  Action
4           4  1978    94.0           Days of Heaven   Drama

                 Actor          Actress           Director  Popularity Awards
0    Banderas, Antonio  Abril, Victoria   Almodóvar, Pedro        68.0     No
1         Bosé, Miguel  Abril, Victoria   Almodóvar, Pedro        68.0     No
2  Walken, Christopher    Adams, Brooke  Cronenberg, David        79.0     No
3        Connery, Sean    Adams, Brooke    Lester, Richard         6.0     No
4        Gere, Richard    Adams, Brooke   Malick, Terrence        14.0     No

Bottom 5 Rows
      Unnamed: 0  Year  Length                     Title Subject  \
1654        1654  1932   226.0  Shadow of the Eagle, The  Action
1655        1655  1989   103.0              Blood & Guns  Action
1656        1656  1988    78.0                 Hot Money   Drama
1657        1657  1977    75.0            Comedy Tonight  Comedy
1658        1658  1991    65.0            Robin Williams  Comedy

                Actor Actress Director  Popularity Awards
1654      Wayne, John      \N       \N        19.0     No
1655    Welles, Orson      \N       \N        43.0     No
1656    Welles, Orson      \N       \N        19.0     No
1657  Williams, Robin      \N       \N        18.0     No
1658  Williams, Robin      \N       \N         4.0     No

 Total percentage of \N values in the dataframe

In [ ]:
(data == '\\N').mean().sum()*100

38.034960819770944

In [ ]:
#Use dropna() method to remove nulls in Length, Subject, Actor, Popularity columns.
#Use replace() method to replace the nulls with ‘Unknown’ in Actress and Director columns.
data.dropna(subset = ['Length', 'Subject', 'Actor', 'Popularity'])
data[['Actress','Director']] =data[['Actress','Director']].replace('\\N','Unknown')
data

,Unnamed: 0,Year,Length,Title,Subject,Actor,Actress,Director,Popularity,Awards
0,0,1990,111.0,Tie Me Up! Tie Me Down!,Comedy,"Banderas, Antonio","Abril, Victoria","Almodóvar, Pedro",68.0,No
1,1,1991,113.0,High Heels,Comedy,"Bosé, Miguel","Abril, Victoria","Almodóvar, Pedro",68.0,No
2,2,1983,104.0,"Dead Zone, The",Horror,"Walken, Christopher","Adams, Brooke","Cronenberg, David",79.0,No
3,3,1979,122.0,Cuba,Action,"Connery, Sean","Adams, Brooke","Lester, Richard",6.0,No
4,4,1978,94.0,Days of Heaven,Drama,"Gere, Richard","Adams, Brooke","Malick, Terrence",14.0,No
...,...,...,...,...,...,...,...,...,...,...
1654,1654,1932,226.0,"Shadow of the Eagle, The",Action,"Wayne, John",Unknown,Unknown,19.0,No
1655,1655,1989,103.0,Blood & Guns,Action,"Welles, Orson",Unknown,Unknown,43.0,No
1656,1656,1988,78.0,Hot Money,Drama,"Welles, Orson",Unknown,Unknown,19.0,No
1657,1657,1977,75.0,Comedy Tonight,Comedy,"Williams, Robin",Unknown,Unknown,18.0,No
1658,1658,1991,65.0,Robin Williams,Comedy,"Williams, Robin",Unknown,Unknown,4.0,No

another method

In [ ]:
#Use replace() method to replace the nulls with ‘Unknown’ in Actress and Director columns.
data.dropna(inplace=True)
data['Actress'] = data['Actress'].replace('\\N', 'Unknown')
data['Director'] = data['Director'].replace('\\N', 'Unknown')
data

,Unnamed: 0,Year,Length,Title,Subject,Actor,Actress,Director,Popularity,Awards
0,0,1990,111.0,Tie Me Up! Tie Me Down!,Comedy,"Banderas, Antonio","Abril, Victoria","Almodóvar, Pedro",68.0,No
1,1,1991,113.0,High Heels,Comedy,"Bosé, Miguel","Abril, Victoria","Almodóvar, Pedro",68.0,No
2,2,1983,104.0,"Dead Zone, The",Horror,"Walken, Christopher","Adams, Brooke","Cronenberg, David",79.0,No
3,3,1979,122.0,Cuba,Action,"Connery, Sean","Adams, Brooke","Lester, Richard",6.0,No
4,4,1978,94.0,Days of Heaven,Drama,"Gere, Richard","Adams, Brooke","Malick, Terrence",14.0,No
...,...,...,...,...,...,...,...,...,...,...
1654,1654,1932,226.0,"Shadow of the Eagle, The",Action,"Wayne, John",Unknown,Unknown,19.0,No
1655,1655,1989,103.0,Blood & Guns,Action,"Welles, Orson",Unknown,Unknown,43.0,No
1656,1656,1988,78.0,Hot Money,Drama,"Welles, Orson",Unknown,Unknown,19.0,No
1657,1657,1977,75.0,Comedy Tonight,Comedy,"Williams, Robin",Unknown,Unknown,18.0,No
1658,1658,1991,65.0,Robin Williams,Comedy,"Williams, Robin",Unknown,Unknown,4.0,No

Explore the trend of average movie lengths over the years between 1980 and 2000 with award status breakdown.

In [ ]:
#Filter the movies based on the 'Year' column from 1980 to 2000
avg_length_1980_2000 = data[(data['Year'] >=1980 ) & (data['Year'] <=2000)]

avg_length_1980_2000

,Unnamed: 0,Year,Length,Title,Subject,Actor,Actress,Director,Popularity,Awards
0,0,1990,111.0,Tie Me Up! Tie Me Down!,Comedy,"Banderas, Antonio","Abril, Victoria","Almodóvar, Pedro",68.0,No
1,1,1991,113.0,High Heels,Comedy,"Bosé, Miguel","Abril, Victoria","Almodóvar, Pedro",68.0,No
2,2,1983,104.0,"Dead Zone, The",Horror,"Walken, Christopher","Adams, Brooke","Cronenberg, David",79.0,No
5,5,1983,140.0,Octopussy,Action,"Moore, Roger","Adams, Maud","Glen, John",68.0,No
6,6,1984,101.0,Target Eagle,Action,"Connors, Chuck","Adams, Maud","Loma, José Antonio de la",14.0,No
...,...,...,...,...,...,...,...,...,...,...
1651,1651,1992,134.0,Red River,Western,"Wayne, John",Unknown,Unknown,16.0,No
1652,1652,1991,52.0,Riders of Destiny,Western,"Wayne, John",Unknown,Unknown,30.0,No
1655,1655,1989,103.0,Blood & Guns,Action,"Welles, Orson",Unknown,Unknown,43.0,No
1656,1656,1988,78.0,Hot Money,Drama,"Welles, Orson",Unknown,Unknown,19.0,No
1658,1658,1991,65.0,Robin Williams,Comedy,"Williams, Robin",Unknown,Unknown,4.0,No

In [ ]:
#Group the data by 'Year' and 'Awards' and calculate the average 'Length'.
year_by_award = avg_length_1980_2000.groupby(['Year' , 'Awards']).Length.mean().reset_index()

# OR
# Filtering movies from 1980 to 2000 and calculating the average length
data_80s_00s = data[(data['Year'] >= 1980) & (data['Year'] <= 2000)]
data_80s_00s_awards = data_80s_00s.groupby(['Year','Awards'])['Length'].mean().reset_index()

#avg_length = data['Length'].mean()
year_by_award
#data_80s_00s_awards

    Year Awards      Length
0   1980     No  106.769231
1   1980    Yes  142.500000
2   1981     No  110.000000
3   1981    Yes  131.400000
4   1982     No  115.206897
5   1982    Yes  154.000000
6   1983     No  100.285714
7   1983    Yes  112.500000
8   1984     No  101.666667
9   1984    Yes  126.750000
10  1985     No  101.428571
11  1985    Yes  118.714286
12  1986     No  100.825581
13  1986    Yes  120.166667
14  1987     No  100.829787
15  1987    Yes  122.800000
16  1988     No  102.530120
17  1988    Yes  123.500000
18  1989     No   99.067416
19  1989    Yes  112.000000
20  1990     No  100.869048
21  1990    Yes  134.000000
22  1991     No  104.379310
23  1991    Yes  118.000000
24  1992     No  104.951220
25  1992    Yes  134.000000
26  1993     No   79.933333
27  1996     No   96.000000
28  1997     No  109.000000

Use the Pandas pivot function to reshape the data suitable for plotting.

In [ ]:
pivot_data = year_by_award.pivot(index = 'Year', columns= 'Awards', values = 'Length')